-- Postgres translation of the SQLite schema in db.js. One competition = one
-- Postgres schema (mirroring one-directory-per-competition on SQLite); these
-- statements are always run with search_path set to that schema, so table
-- names are unqualified. Kept in lockstep with SCHEMA in db.js.
--
-- Dialect notes vs SQLite:
--   INTEGER PRIMARY KEY  -> GENERATED BY DEFAULT AS IDENTITY (explicit ids still allowed)
--   REAL                 -> DOUBLE PRECISION
--   attempted_at         -> BIGINT (Date.now() overflows a Postgres INTEGER)
--   PRAGMAs              -> dropped (WAL/foreign key enforcement are defaults)

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  position INTEGER NOT NULL,
  voting_locked INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS criteria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  position INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS category_weights (
  category_id INTEGER NOT NULL REFERENCES categories(id),
  criterion_id INTEGER NOT NULL REFERENCES criteria(id),
  weight DOUBLE PRECISION NOT NULL CHECK (weight >= 0),
  PRIMARY KEY (category_id, criterion_id)
);

CREATE TABLE IF NOT EXISTS panels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category_id INTEGER NOT NULL REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS judges (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  pin_hash TEXT NOT NULL,
  panel_id INTEGER REFERENCES panels(id),
  role TEXT NOT NULL DEFAULT 'judge' CHECK (role IN ('judge','admin'))
);

CREATE TABLE IF NOT EXISTS entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER NOT NULL REFERENCES categories(id),
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  team TEXT NOT NULL DEFAULT '',
  position INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS scores (
  judge_id INTEGER NOT NULL REFERENCES judges(id),
  entry_id INTEGER NOT NULL REFERENCES entries(id),
  criterion_id INTEGER NOT NULL REFERENCES criteria(id),
  score INTEGER NOT NULL CHECK (score BETWEEN 1 AND 5),
  updated_at TEXT NOT NULL,
  PRIMARY KEY (judge_id, entry_id, criterion_id)
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS login_attempts (
  employee_id TEXT NOT NULL,
  attempted_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_login_attempts ON login_attempts (employee_id, attempted_at);
